# Python Data Structures



> This notebook is largely based on the notebook "Lesson 5: Python Data Structures" from Pragmatic AI Labs.

https://colab.research.google.com/github/paiml/python_for_datascience/blob/master/Lesson5_Python_For_Data_Science_Python_Data_structure.ipynb#scrollTo=aCBZvOZn3V6D


## Topics Covered
##### 1-List
##### 2-Tuple
##### 3-Set
##### 4-Dictionaries
##### 5-Numpy Arrays
##### 6-Pandas Dataframe

## Lists
 

### Creating an empty list

In [1]:
empty = []

empty

[]

In [2]:
empty= list()
empty

[]

### Using square brackets with initial values

In [5]:
numbers = [1, 2, 3]
numbers




[1, 2, 3]

In [6]:
a=list()
a

[]

### Creating using multiplication

In [ ]:
num_players = 10
scores = [0] * num_players
scores

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

### Mixing data types
Lists can contain multple data types

In [9]:
mixed = ['a', 1, 2.0, [13], {}]
mixed

['a', 1, 2.0, [13], {}]

### Indexing
Items in lists can be accessed using indices 

#### Access first item

In [10]:
numbers

[1, 2, 3]

In [13]:
numbers[3]


IndexError: list index out of range

#### Access last item

In [15]:
numbers[-1]

3

#### Access any item

In [16]:
numbers[4]

IndexError: list index out of range

### Adding to a list

#### Append to the end of a list

In [19]:
letters = ['a']
letters.append('c')
letters

['a', 19]

#### Insert at beginning of list

In [20]:
letters.insert(0, 'b')
letters

['b', 'a', 19]

#### Insert at arbitrary position

In [8]:
letters.insert(2, 'c')
letters

['b', 'a', 'c', 'c']

#### Extending with another list

In [28]:
more_letters = ['e', 'f', 'g']
letters.extend(more_letters)
letters

['a', 'b', 'c', 'e', 'f', 'g']

In [29]:
more_letters
letters.append(more_letters)
letters

['a', 'b', 'c', 'e', 'f', 'g', ['e', 'f', 'g']]

### Change item at some position

In [10]:
letters[3] = 'd'
letters

['b', 'a', 'c', 'd', 'e', 'f', 'g']

### Swap two items

In [21]:
letters[0], letters[1]

('b', 'a')

In [22]:
letters[0], letters[1] = letters[1], letters[0]
letters

['a', 'b', 19]

### Removing items from a list

#### Pop from the end

In [23]:
letters = ['a', 'b', 'c', 'd', 'e', 'f']
letters.pop()
letters

['a', 'b', 'c', 'd', 'e']

In [24]:
letters.pop()
letters

['a', 'b', 'c', 'd']

In [25]:
letters.pop()
letters

['a', 'b', 'c']

#### Pop by index

In [13]:
letters.pop(2)
letters

['a', 'b', 'd', 'e']

#### Remove specific item

In [14]:
letters.remove('d')
letters

['a', 'b', 'e']

## Tuples


### Create tuple using brackets

In [26]:
tup = (1, 2, 3)
tup


(1, 2, 3)

### Create tuple with commas

In [30]:
tup = 1, 2, 3
tup

(1, 2, 3)

### Create empty tuple

In [32]:
tup = ()
tup

()

### Create tuple with single item

In [33]:
tup = 1,
tup

(1,)

## List ve Tuple arasindaki benzer ozellikler


### Check item in sequence

In [17]:
3 in (1, 2, 3, 4, 5)

True

### Check item not in sequence

In [16]:
'a' not in [1, 2, 3, 4, 5]

True

### Slicing

#### Setting start, slice to the end

In [ ]:
letters = 'a', 'b', 'c', 'd', 'e', 'f'
letters[3:4]


('d',)

#### Set end, slice from beginning

In [35]:
letters[:1]

['a']

#### Index from end of sequence

In [ ]:
letters[-4:]

('c', 'd', 'e', 'f')

In [36]:
liste= [1,1,1,1,1]
liste

[1, 1, 1, 1, 1]

In [39]:
numbers = [5, 2, 9, 1, 7]
numbers[1:3]
numbers[1:4]

[2, 9, 1]

# Quiz - Lists

#### 1- Can a list object have the same elements inside?
#### 2- Given the list numbers = [5, 2, 9, 1, 7], what is the output of numbers[2]?
#### 3- How would you append the number 10 to the end of the numbers list?
#### 4- What is the difference in output between numbers[1:3] and numbers[1:4]?
#### 5- If tuple_nums = (3, 8, 1, 6), can you modify the value at index 1 to be 5? Explain why or why not.



# Dictionaries

### Create an empty dict 

In [ ]:
dictionary = {}
dictionary

{}

In [41]:
dictionary = dict()
dictionary

{}

### Use curley braces to create a dictionary with initial key/values

In [42]:
dictionary = {'key-1': 'value-1',
              'key-2': 'value-2'}

dictionary

{'key-1': 'value-1', 'key-2': 'value-2'}

### Access value using key

In [ ]:
dictionary['key-1']

'value-1'

### Add a key/value pair to an existing dictionary

In [44]:
dictionary['key-3'] = 'value-3'
dictionary['Yavuz'] = 'Cakir'

dictionary

{'key-1': 'value-1', 'key-2': 'value-2', 'key-3': 'value-3', 'Yavuz': 'Cakir'}

### Update value for existing key

In [45]:
dictionary['key-2'] = 'new-value-2'
dictionary['key-2']

'new-value-2'

### Get keys

In [46]:
dictionary

{'key-1': 'value-1',
 'key-2': 'new-value-2',
 'key-3': 'value-3',
 'Yavuz': 'Cakir'}

In [48]:
dictionary.values()

dict_values(['value-1', 'new-value-2', 'value-3', 'Cakir'])

In [50]:
list(dictionary.keys())

('key-1', 'key-2', 'key-3', 'Yavuz')

### Get values

In [58]:
dictionary.keys()

dict_keys(['key-2', 'key-3', 'Yavuz'])

### Get iterable keys and items

In [69]:
dictionary['Pinar_Ekici'] = ['Ekici',2003,"Izmir"]


In [72]:
dictionary.items()

dict_items([('key-2', 'new-value-2'), ('key-3', 'value-3'), ('Yavuz', 'Cakir'), ('Pinar', ['Ekici', 2003, 'Izmir']), ('Pinar_Ekici', ['Ekici', 2003, 'Izmir'])])

In [73]:
dictionary

{'key-2': 'new-value-2',
 'key-3': 'value-3',
 'Yavuz': 'Cakir',
 'Pinar': ['Ekici', 2003, 'Izmir'],
 'Pinar_Ekici': ['Ekici', 2003, 'Izmir']}

### Use items in for loop

In [78]:
for yavuz, cakir in dictionary.items():
  print(f"{yavuz}: {cakir}")

key-2: new-value-2
key-3: value-3
Yavuz: Cakir
Pinar: ['Ekici', 2003, 'Izmir']
Pinar_Ekici: ['Ekici', 2003, 'Izmir']


### Check if dictionary has key
The 'in' syntax we used with sequences checks the dicts keys for membership.

In [86]:
'Yavuz' in dictionary

False

### Remove item

In [83]:
del(dictionary['Pinar'])
dictionary

{'key-2': 'new-value-2',
 'key-3': 'value-3',
 'Pinar_Ekici': ['Ekici', 2003, 'Izmir']}

### Keys must be immutable

#### List as key
Lists are mutable and not hashable

In [57]:
items = ('item-1', 'item-2', 'item-3')

map = {}

map[items] = "some-value"
map

{('item-1', 'item-2', 'item-3'): 'some-value'}

#### Tuple as a key
Tuples are immutable and hence hashable

In [ ]:
items = 'item-1', 'item-2', 'item-3'
map = {}
map[items] = "some-value"

map

{('item-1', 'item-2', 'item-3'): 'some-value'}

#  QUIZ
#### 1- Create a dictionary called student with keys 'name', 'age', and 'grade', and assign appropriate values.
#### 2- How would you access the 'age' of the student from the student dictionary?
#### 3- Add a new key-value pair 'major': 'Computer Science' to the student dictionary.
#### 4- If you try to access a key that doesn't exist in a dictionary, what happens?



# Sets

### Create set from tuple or list

In [ ]:
letters = 'a', 'a', 'a', 'b', 'c'
unique_letters = set(letters)
unique_letters

{'a', 'b', 'c'}

In [88]:
letters = [1,2,3,3]
letters

[1, 2, 3, 3]

In [89]:
set(letters)

{1, 2, 3}

### Create set from a string

In [93]:
unique_chars_list = list('mississippi')
unique_chars_list

['m', 'i', 's', 's', 'i', 's', 's', 'i', 'p', 'p', 'i']

In [ ]:
unique_chars = set('mississippi')
unique_chars

{'i', 'm', 'p', 's'}

### Create set using curley braces

In [91]:
unique_num = {1, 1, 2, 3, 4, 5, 5}
#or set()
unique_num

{1, 2, 3, 4, 5}

In [ ]:
set_a = dict()

### Adding to a set

In [94]:
unique_num.add(6)
unique_num

{1, 2, 3, 4, 5, 6}

### Popping from a set
Pop method removes and returns a random element of the set

In [96]:
unique_num.pop()

1

### Indexing
Sets have no order, and hence cannot be accessed via indexing

In [97]:
unique_num[4]

TypeError: 'set' object is not subscriptable

### Checking membership

In [98]:
3 in unique_num

True

### Set operations

In [24]:
s1 = { 1 ,2 ,3 ,4, 5, 6, 7}
s2 = { 0, 2, 4, 6, 8 }

#### Items in first set, but not in the second

In [25]:
s1 - s2

{1, 3, 5, 7}

#### Items in either or both sets

In [ ]:
s1 | s2

{0, 1, 2, 3, 4, 5, 6, 7, 8}

#### Items in both sets

In [ ]:
s1 & s2

{2, 4, 6}

In [ ]:
list()
set()
dict()
list=[]
set=
tuple
dict={}

# Questions

### How to add elemnts into list and set? 
### How to create List-set-Dict, with an alternative method?

#### Create two sets: set1 = {1, 2, 3, 4} and set2 = {3, 4, 5, 6}. What is the output of set1.union(set2)?
#### What is the output of set1.intersection(set2)?



# Work with the numpy array


###### Numpy is an opened source numerical computing libary for python. 
###### As with many high performance Python libraries, significant parts of it are in fact written in C/C++

### Create a numpy array from a list of lists

In [ ]:
import numpy as np


In [7]:
import numpy as np

list_of_lists = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

np_array = np.array(list_of_lists)

np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Initialize an array of zeros

In [ ]:
zeros_array = np.zeros( (4, 5) )
zeros_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Initialize and array of ones

In [ ]:
ones_array = np.ones( (6, 6) )
ones_array

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Using reshape

In [1]:
nine.reshape(3,3)

NameError: name 'nine' is not defined

### Introspection

#### Get the data type

In [4]:
np_array.dtype

dtype('int64')

#### Get the array's shape

In [8]:
np_array.shape

(4, 4)

In [9]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Get the number of items in the array

In [ ]:
np_array.size

16

#### Get the size of the array in bytes

In [ ]:
np_array.nbytes

128

### Setting the data type

#### dtype parameter

In [ ]:
np_array = np.array(list_of_lists, dtype=np.int8)
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

#### Size reduction

In [ ]:
np_array.nbytes

16

### Array Slicing


*   Slicing can be used to get a view reprsenting a sub-array.
*   The slice is a view to the original array, the data is not copied to a new data structure
*   The slice is taken in the form: array[ rows, columns ]






In [ ]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int8)

In [14]:
np_array[2:, :3]

array([[ 9, 10, 11],
       [13, 14, 15]])

In [16]:
np_array[:1, 3:]

array([[4]])

### Math operations


*   Unlike a unlike nested lists, matrix operations perform mathimatical operations on data



#### Create two 3 x 3 arrays

In [20]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np_array_1 = np.arange(9).reshape(3,3)
np_array_1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
np_array_2 = np.arange(10, 19).reshape(3,3)
np_array_2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

#### Multiply the arrays

In [ ]:
np_array_1 * np_array_2

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

#### Add the arrays

In [ ]:
np_array_1 + np_array_2

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

### Matrix operations

#### Transpose

In [21]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
np_array.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]], dtype=int8)

## Pandas DataFrame
*   One of the most highly leveraged data structures for data science
*   A table-like two dimensional data structure.
*   A new and faster alternative- Polars



### Create a DataFrame- Who joined the class

In [24]:
import pandas as pd
first_names = ['Birsen', 'Musa', 'Duygu', 'Elif', 'Ozlem', 'Ebru', 'Emir', 'Elyar', 'Yavuz']
last_names = ['Yurtdas', 'Kirgezen', 'Keremitci', 'Duymaz', 'Tuna', 'Kocakaya', 'Amiritabat', 'Bafandeh','Cakir']
ages = [20, 13, 21, 15, 23, 30, 40, 50,80]

df = pd.DataFrame({ 'first_name': first_names, 'last_name': last_names, 'age': ages})
df

first_name   last_name  age
0     Birsen     Yurtdas   20
1       Musa    Kirgezen   13
2      Duygu   Keremitci   21
3       Elif      Duymaz   15
4      Ozlem        Tuna   23
5       Ebru    Kocakaya   30
6       Emir  Amiritabat   40
7      Elyar    Bafandeh   50
8      Yavuz       Cakir   80

### Head - looking at the top

In [26]:
df.head(5)

first_name  last_name  age
0     Birsen    Yurtdas   20
1       Musa   Kirgezen   13
2      Duygu  Keremitci   21
3       Elif     Duymaz   15
4      Ozlem       Tuna   23

### Setting number of rows returned with head

In [27]:
df.head(3)

first_name  last_name  age
0     Birsen    Yurtdas   20
1       Musa   Kirgezen   13
2      Duygu  Keremitci   21

### Tail - looking at the bottom

In [28]:
df.tail(2)

first_name last_name  age
7      Elyar  Bafandeh   50
8      Yavuz     Cakir   80

### Describe - descriptive statistics

NameError: name 'summary' is not defined

In [29]:
df.describe()

age
count   9.000000
mean   32.444444
std    21.477378
min    13.000000
25%    20.000000
50%    23.000000
75%    40.000000
max    80.000000

### Access one column

In [30]:
df

first_name   last_name  age
0     Birsen     Yurtdas   20
1       Musa    Kirgezen   13
2      Duygu   Keremitci   21
3       Elif      Duymaz   15
4      Ozlem        Tuna   23
5       Ebru    Kocakaya   30
6       Emir  Amiritabat   40
7      Elyar    Bafandeh   50
8      Yavuz       Cakir   80

In [33]:
df['age']

0    20
1    13
2    21
3    15
4    23
5    30
6    40
7    50
8    80
Name: age, dtype: int64

### Slice a column

In [34]:
df['first_name'][4:]

4    Ozlem
5     Ebru
6     Emir
7    Elyar
8    Yavuz
Name: first_name, dtype: object

### Use conditions to filter

In [36]:
df['age'] > 40

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
Name: age, dtype: bool

In [38]:
df[df['age'] > 30]

first_name   last_name  age
6       Emir  Amiritabat   40
7      Elyar    Bafandeh   50
8      Yavuz       Cakir   80

## 5.6 Use the pandas Series


*   A one dimensional labeled array
*   Contains data of only one type
*   Similar to a column in a spreedsheet




### Create a series

In [39]:
pd_series = pd.Series( [1, 2, 3 ] )
pd_series

0    1
1    2
2    3
dtype: int64

### Series introspection methods

In [ ]:
f"This series is made up of {pd_series.size} items whose data type is {pd_series.dtype}"

'This series is made up of 3 items whose data type is int64'

### A Pandas DataFrame is composed of Pandas Series.

In [40]:
age = df.age
type( age )

pandas.core.series.Series

### Some useful helper methods of a Series

#### mean

In [43]:
pd_series = pd.Series([ 1, 2, 3, 5, 6, 6, 6, 7, 8])
pd_series.mean()

4.888888888888889

#### Unique

In [45]:
pd_series.unique()

array([1, 2, 3, 5, 6, 7, 8])

In [54]:
list(set(pd_series[pd_series.duplicated()]))

[6]

In [62]:
np.array(pd_series.unique()).pop(np.array(list(set(pd_series[pd_series.duplicated()]))))

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [61]:
np.array(list(set(pd_series[pd_series.duplicated()])))

array([6])

In [73]:
pd_series.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7    False
8    False
dtype: bool

In [64]:
uniq = pd_series[~pd_series.duplicated(keep=False)]
uniq

0    1
1    2
2    3
3    5
7    7
8    8
dtype: int64

#### Max

In [41]:
pd_series.min()

1